package com.ridedecider.app.domain.model

/**
 * Razones estructuradas que justifican la recomendación emitida por el DecisionEngine.
 */
enum class DecisionReason {
    ACCEPT_HIGH_PROFITABILITY,
    REJECT_EXCESSIVE_PICKUP_DISTANCE,
    REJECT_EXCESSIVE_PICKUP_TIME,
    REJECT_LOW_HOURLY_RATE,
    REJECT_LOW_KM_RATE,
    REJECT_LOW_NET_PROFIT,
    REJECT_LOW_NET_HOURLY_RATE,
    UNKNOWN_MISSING_FARE,
    UNKNOWN_MISSING_PICKUP_DISTANCE,
    UNKNOWN_MISSING_PICKUP_TIME,
    UNKNOWN_MISSING_TRIP_DISTANCE,
    UNKNOWN_MISSING_TRIP_TIME,
    UNKNOWN_INVALID_DATA,
    CONTEXT_BELOW_REQUIRED_HOURLY_RATE,
    CONTEXT_ABOVE_REQUIRED_HOURLY_RATE,
    CONTEXT_DAILY_TARGET_REACHED
}
